import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const toolDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(toolDirectory, '..');
const assetDirectory = path.join(repositoryRoot, 'project-assets', 'omato-asc');
const outputPath = path.join(repositoryRoot, 'embedded-device-assets.js');
const filenames = [
  'device-detail.png',
  'device-list.png',
  'device-practice.png',
  'device-scan.png',
  'device-study.png',
  'device-test.png',
  'device-widget.png'
];

const embeddedAssets = Object.fromEntries(
  filenames.map((filename) => {
    const filePath = path.join(assetDirectory, filename);
    const base64 = fs.readFileSync(filePath).toString('base64');
    return [`project-assets/omato-asc/${filename}`, `data:image/png;base64,${base64}`];
  })
);

const generatedSource = [
  '/* Generated by tools/generate_embedded_device_assets.mjs. Do not edit by hand. */',
  `globalThis.OMATO_EMBEDDED_DEVICE_ASSETS = Object.freeze(${JSON.stringify(embeddedAssets)});`,
  ''
].join('\n');

if (process.argv.includes('--check')) {
  const existingSource = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : '';
  if (existingSource !== generatedSource) {
    console.error('embedded-device-assets.js is out of date');
    process.exitCode = 1;
  }
} else {
  fs.writeFileSync(outputPath, generatedSource);
  console.log(`Wrote ${path.relative(repositoryRoot, outputPath)}`);
}
