import json,hashlib,struct,html,zipfile
from pathlib import Path
root=Path('/Users/lucas/Developer/Omato');r=root/'framed-screenshot-builder';name='spanish-meta-carousel-stories-20260927';pr=r/'projects'/f'{name}.json';p=json.loads(pr.read_text());out=root/'marketing-screenshots/ads/LanguageLearner-Eng-Spa/meta-carousel-stories-20260927'
def sha(f):return hashlib.sha256(f.read_bytes()).hexdigest()
def overlap(a,b):return a['x']<b['x']+b['width'] and a['x']+a['width']>b['x'] and a['y']<b['y']+b['height'] and a['y']+a['height']>b['y']
def inside(b):return b['x']>=86.4 and b['x']+b['width']<=1353.6 and b['y']>=358.4 and b['y']+b['height']<=1664
metrics=json.loads((out/'layout-metrics.json').read_text());assets=[];cards=[]
for s,met in zip(p['scenes'],metrics):
 ls={l['id']:l for l in s['layers']};dev=ls['device'];db={**dev,'height':dev['width']*dev['aspectRatio']}
 assert not overlap(met['text'][0]['bounds'],met['text'][1]['bounds'])
 for t in met['text']:
  assert inside(t['bounds']),(s['id'],t);assert not overlap(t['bounds'],db),(s['id'],t);assert max(t['lineWidths'])<=t['bounds']['width']
 rr=s['essentialDeviceRegion']['sourceRect'];sc=dev['width']/1350;proof={k:rr[k]*sc+(dev[k] if k in ['x','y'] else 0) for k in rr};assert inside(proof),(s['id'],proof)
 png=out/s['filename'];assert struct.unpack('>II',png.read_bytes()[16:24])==(1440,2560)
 assert png.stat().st_size<30000000
 sources=[{'path':str((r/l['src']).resolve().relative_to(root)),'sha256':sha(r/l['src'])} for l in s['layers'] if l['type']=='image']
 asset={'id':f'AD-LNG-EN-ES-META-STORIES-20260927-{s["id"].upper()}','path':str(png.relative_to(root)),'sha256':sha(png),'bytes':png.stat().st_size,'width':1440,'height':2560,'audience':'English-speaking Spanish learners','copy_locale':'en-US','title':ls['title']['text'],'subtitle':ls['subtitle']['text'],'sources':sources,'status':'awaiting-owner-artwork-review','provider_preview':'pending; not uploaded','essential_proof':s['essentialDeviceRegion'],'project':str(pr.relative_to(root)),'project_sha256':sha(pr)};assets.append(asset)
 url='marketing-media/ads/LanguageLearner-Eng-Spa/meta-carousel-stories-20260927/'+s['filename'];cards.append(f'<article><h2>{html.escape(s["name"])}</h2><a href="{url}"><img src="{url}" alt="{html.escape(s["name"])}"></a></article>')
manifest={'revision':name,'status':'local_review_only','repair_target_ad':'52596396219722','placement':'Instagram Stories carousel','live_mutation':False,'copy_and_order':'Unchanged from approved square carousel; line breaks adapted','provider_boundary':'9:16 is Meta documented alternative to square Stories adaptation, not proof this caption defect is eliminated. Must verify every card in actual Stories preview after owner artwork approval, then scoped save/readback.','provenance':'Reused existing native screenshots, iPhone 17 Pro silver frames and photographic backgrounds; no new captures, app build verification, generated UI or tracking. Raw/frame source hashes in marketing-screenshots/framed/LanguageLearner-Eng-Spa/source-manifest.json.','assets':assets,'validation':'Dimensions, original text equivalence, no text overlap, safe bounds of text and explicit UI proof verified; local contrast check and browser visual review recorded alongside.'}
(out/'manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
(r/f'{name}.html').write_text('''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Omato · Stories carousel review</title><style>*{box-sizing:border-box}body{margin:0;background:#f4f1e9;color:#20251e;font:16px system-ui}main{padding:28px;max-width:1240px;margin:auto}h1,h2{font-family:"Bodoni 72",serif}h1{font-size:38px}h2{font-size:22px;min-height:54px}p{max-width:950px;line-height:1.5}a{color:inherit}.cards{display:flex;flex-wrap:wrap;gap:28px}article{width:360px;max-width:100%}img{display:block;width:100%;height:auto}.button{display:inline-block;padding:12px 18px;background:#fff;border-radius:24px;margin:8px 12px 14px 0}</style><main><h1>Stories carousel · contrast repair</h1><p>Seven full-height 9:16 cards for Instagram Stories. Same copy, card order and app screenshots as the approved Feed carousel. Feed images stay unchanged.</p><p><strong>Local proposal — not uploaded or published.</strong> This avoids square-image auto-adaptation. Meta’s caption treatment and CTA still need checking in the actual placement preview; these images alone do not prove the issue is fixed.</p><a class="button" href="editor.html?project=projects/'''+name+'''.json">Review in the editor</a><a class="button" href="marketing-media/ads/LanguageLearner-Eng-Spa/meta-carousel-stories-20260927/manifest.json">Manifest</a><p>Phone-width previews (360 px). Selection and Study place the copy beside a large complete phone, keeping the highlighted word and revealed definition clear of the Stories overlay area.</p><div class="cards">'''+''.join(cards)+'''</div></main></html>''')
with zipfile.ZipFile(out/'stories-carousel-review.zip','w',zipfile.ZIP_DEFLATED) as z:
 for f in out.glob('*.png'): z.write(f,f.name)
 z.write(out/'manifest.json','manifest.json');z.write(pr,pr.name)
print('Validated and packaged',len(assets),'cards')
